
notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

language: python

cache: pip

python:
  - "3.12"

# command to install dependencies
install:
  - pip install click==8.1.7
  - pip install codeallybasic==1.7.0
  - pip install html-testRunner==1.2.1
\

# command to run tests
script:
  - unittests
