
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.13
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y jq
            pip install --upgrade pip
            pip install wheel
            pip install setuptools
            pip install click==8.1.8
            pip install buildlackey~=1.7.0
            pip install html-testRunner~=1.2.1
            pip install codeallybasic==1.8.0
      - run:
            name: run tests
            command: | 
              unittests -v loud
