
from unittest import TestSuite
from unittest import main as unitTestMain

from platform import platform as osPlatform

from codeallybasic.UnitTestBase import UnitTestBase

from latestversions.LatestVersions import MAC_OS_JQ_PATH
from latestversions.LatestVersions import NON_MAC__OS_JQ_PATH
from latestversions.LatestVersions import LatestVersions
from latestversions.LatestVersions import THE_GREAT_MAC_PLATFORM


class TestLatestVersions(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 10 September 2024
    """
    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testRunCommandFail(self):
        status: int = LatestVersions.runCommand('/bogus/bin/fail')
        self.assertNotEqual(0, status, 'This should fail')

    def testRunCommandPass(self):
        platform: str = osPlatform(terse=True)
        if platform.startswith(THE_GREAT_MAC_PLATFORM) is True:
            status: int = LatestVersions.runCommand(MAC_OS_JQ_PATH)
        else:
            status = LatestVersions.runCommand(NON_MAC__OS_JQ_PATH)

        self.assertEqual(0, status, 'This should pass')


def suite() -> TestSuite:

    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestLatestVersions))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
